### DISCUSSION TITLE
Bubble lualine is not working properly?

### DISCUSSION THREAD

**Discussion by prsh11** [nvim-lualine/lualine.nvim#500] [Q&A] [answered]
The circles are not right

![image](https://user-images.githubusercontent.com/67903361/146747088-9ae9a4b2-12a0-40d0-8306-d4db141ffef8.png)

Here my config 
```lua
local colors = {
  blue   = '#80a0ff',
  cyan   = '#79dac8',
  black  = '#080808',
  white  = '#c6c6c6',
  red    = '#ff5189',
  violet = '#d183e8',
  grey   = '#303030',
}

local bubbles_theme = {
  normal = {
    a = { fg = colors.black, bg = colors.violet },
    b = { fg = colors.white, bg = colors.grey },
    c = { fg = colors.black, bg = colors.black },
  },

  insert = { a = { fg = colors.black, bg = colors.blue } },
  visual = { a = { fg = colors.black, bg = colors.cyan } },
  replace = { a = { fg = colors.black, bg = colors.red } },

  inactive = {
    a = { fg = colors.white, bg = colors.black },
    b = { fg = colors.white, bg = colors.black },
    c = { fg = colors.black, bg = colors.black },
  },
}

require('lualine').setup {
  options = {
    theme = bubbles_theme,
    component_separators = '|',
    section_separators = { left = '', right = '' },
  },
  sections = {
    lualine_a = {
      { 'mode', separator = { left = '' }, right_padding = 2 },
    },
    lualine_b = { 'filename', 'branch' },
    lualine_c = { 'fileformat' },
    lualine_x = {},
    lualine_y = { 'filetype', 'progress' },
    lualine_z = {
      { 'location', separator = { right = '' }, left_padding = 2 },
    },
  },
  inactive_sections = {
    lualine_a = { 'filename' },
    lualine_b = {},
    lualine_c = {},
    lualine_x = {},
    lualine_y = {},
    lualine_z = { 'location' },
  },
  tabline = {},
  extensions = {},
}
```

**Comment by shadmansaleh** [comment]
It's most likely an issue with the font you are using . Try a different nerd pathced font https://github.com/ryanoasis/nerd-fonts#patched-fonts

**Reply by prsh11** [reply]
I am using JetBrains Mono Nerd font, still not getting it. Is it something related to alacritty config?.  I have installed `nerd-fonts-jetbrains-mono` aur package. Changed my font in the alacritty config to `JetBrains Mono Nerd Font`

**Reply by shadmansaleh** [reply]
I don't know. I've never used alacritty . I've been using fira code on kitty and bubbles works fine.

**Comment by fitrh** [comment, marked as answer]
Use the right font name in your terminal emulator config,
run `fc-list : family style | grep 'font name'` to find out the correct name

Edit:
For JetBrains Mono, the nerd font name is **`JetBrainsMono Nerd Font`**,
not `JetBrains Mono Nerd Font`

**Reply by prsh11** [reply]
still the same problem

![image](https://user-images.githubusercontent.com/67903361/146906870-be8ceb16-7ed1-4f5c-85a0-32a68e666bfc.png)

**Reply by fitrh** [reply]
This is my config on alacritty and its works fine

```yaml
font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular
  italic:
    family: JetBrainsMono Nerd Font
    style: Italic
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
  bold_italic:
    family: JetBrainsMono Nerd Font
    styel: Bold Italic
  size: 10.0
  offset:
    x: 0
    y: 0
```
